steps:
  # Step 0: Authenticate Docker Hub using environment variables
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "${_DOCKER_PASSWORD}" | docker login -u "${_DOCKER_USERNAME}" --password-stdin
    secretEnv:
      - '_DOCKER_USERNAME'
      - '_DOCKER_PASSWORD'

  # Step 1: Build the Spring Boot application
  - name: 'maven:3.8.4-openjdk-11'
    entrypoint: 'mvn'
    args: ['clean', 'install']

  # Step 2: Build the Docker image
  - name: 'docker'
    args: ['build', '-t', 'ganshekar/my-springboot-app:$COMMIT_SHA', '.']

  # Step 3: Push the Docker image to Docker Hub
  - name: 'docker'
    args: ['push', 'ganshekar/my-springboot-app:$COMMIT_SHA']

  # Step 4: Deploy the Docker image to Cloud Run
  - name: 'docker.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-springboot-app'
      - '--image=docker.io/ganshekar/my-springboot-app:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'ganshekar/my-springboot-app:$COMMIT_SHA'

secrets:
  - name: 'projects/ds-ms-microservices/secrets/docker-username/versions/latest'
    secretEnv:
      _DOCKER_USERNAME: 'ganshekar'

  - name: 'projects/ds-ms-microservices/secrets/docker-password/versions/latest'
    secretEnv:
      _DOCKER_PASSWORD: 'Ganshekar@1991'

substitutions:
  _DOCKER_USERNAME: 'projects/ds-ms-microservices/secrets/docker-username/versions/latest'
  _DOCKER_PASSWORD: 'projects/ds-ms-microservices/secrets/docker-password/versions/latest'
