steps:
  # Step 1: Build the Spring Boot application
  - name: 'maven:3.8.4-openjdk-11'
    entrypoint: 'mvn'
    args: ['clean', 'install']

  # Step 2: Build the Docker image
  - name: 'docker'
    args: ['build', '-t', 'ganshekar/my-springboot-app:$COMMIT_SHA', '.']

  # Step 3: Push the Docker image to Docker Hub (if needed)
  - name: 'docker'
    args: ['push', 'ganshekar/my-springboot-app:$COMMIT_SHA']

  # Step 4: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy my-springboot-app \
          --image=docker.io/ganshekar/my-springboot-app:$COMMIT_SHA \
          --platform=managed \
          --region=us-central1 \
          --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'ganshekar/my-springboot-app:$COMMIT_SHA'
