name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Build Docker image
      run: docker build -t ganshekar/my-springboot-app:$GITHUB_SHA .

    - name: Push Docker image to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        docker push ganshekar/my-springboot-app:$GITHUB_SHA

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v0.3.0
      with:
        service: my-springboot-app
        image: ganshekar/my-springboot-app:$GITHUB_SHA
        region: us-central1
        credentials: ${{ secrets.GCP_SA_KEY }}
